### ISSUE TITLE
Problem starting the app

### ISSUE THREAD

**Issue by CadisRaziel** [newrelic/newrelic-flutter-agent#51]
I followed the pub.dev documentation correctly, but I'm having this problem:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Vitor\Documents\trabalho\instalador\android\build.gradle' line: 27

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Failed to notify project evaluation listener.
      > com/android/build/api/variant/ScopedArtifacts$Scope

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

I've added the dependencies to their correct folders:
apply plugin:  android>app>build.gradle
--------------
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'newrelic'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

dependencies: android>build.gradle
--------------
 buildscript {
    ext.kotlin_version = '1.7.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.2.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "com.newrelic.agent.android:agent-gradle-plugin:7.0.0"
    }
} 

I'm using dart version 3
Is the dependency version correct?
what could it be?

**Comment by CadisRaziel** [comment]
maybe this update would fix my problem, but i have a single dependency that depends on the version 'classpath 'com.android.tools.build:gradle:7.2.0', if i change it my app will break =(


I changed the version to 6 'classpath "com.newrelic.agent.android:agent-gradle-plugin:6.0.0"' and kept the tools com.android.tools.build:gradle:7.2.0, but in the debug it gave me the following message: [newrelic.error] [InvocationDispatcher] Class[unknown] ignored: JDK not supported

and then it builds the project, will I be able to use the new relic without any problems even though it gives this error?


I also had this error in the debug:
══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
The following assertion was thrown during runApp:
Zone mismatch.
The Flutter bindings were initialized in a different zone than is now being used. This will likely
cause confusion and bugs as any zone-specific configuration will inconsistently use the
configuration of the original binding initialization zone or this zone based on hard-to-predict
factors such as which zone was active when a particular callback was set.
It is important to use the same zone when calling `ensureInitialized` on the binding as when calling
`runApp` later.
To make this warning fatal, set BindingBase.debugZoneErrorsAreFatal to true before the bindings are
initialized (i.e. as the first statement in `void main() { }`).

When the exception was thrown, this was the stack:
#0 BindingBase.debugCheckZone.<anonymous closure> (package:flutter/src/foundation/binding.dart:503:29)
#1 BindingBase.debugCheckZone (package:flutter/src/foundation/binding.dart:508:6)
#2 runApp (package:flutter/src/widgets/binding.dart:1093:18)
#3 main.<anonymous closure>.<anonymous closure> (package:installer/main.dart:59:7)
<asynchronous suspension>
(elided 2 frames from dart:async)

**Comment by CadisRaziel** [comment]
ok, Thank you
